import { useState } from "react";
import { analyzeAndSaveAdvertising, listAdvertisingAnalysisReports, type AdvertisingAnalysis } from "./api";

export function AdvertisingAnalysisView({ workspaceId }: { workspaceId: string }) {
  const [reports, setReports] = useState<AdvertisingAnalysis[]>([]);
  const [message, setMessage] = useState("广告分析只生成建议，不修改广告配置");
  const [busy, setBusy] = useState(false);
  const analyze = async () => { setBusy(true); try { const report = await analyzeAndSaveAdvertising(workspaceId, { spend_minor: 3000, ad_sales_minor: 10000, total_sales_minor: 20000, keyword_count: 10, unconverted_keyword_count: 2, acos_alert_percent: 20 }); setReports((current) => [report, ...current]); setMessage("广告分析报告已保存"); } catch (error) { setMessage(error instanceof Error ? error.message : "广告分析失败"); } finally { setBusy(false); } };
  const load = async () => { setBusy(true); try { setReports(await listAdvertisingAnalysisReports(workspaceId)); setMessage("已加载广告分析历史"); } catch (error) { setMessage(error instanceof Error ? error.message : "广告历史加载失败"); } finally { setBusy(false); } };
  return <div className="view-content"><section className="page-heading compact"><div><p className="eyebrow">报告与智能助手 / AI-005</p><h1>广告分析</h1><p>汇总 ACOS、TACOS、ROI 与关键词风险，生成只读建议。</p></div></section><section className="panel"><div className="section-heading"><div><p className="eyebrow">只读分析</p><h2>广告经营信号</h2></div><div className="button-row"><button className="secondary-button" disabled={busy} onClick={() => void analyze()}>运行并保存分析</button><button className="secondary-button" disabled={busy} onClick={() => void load()}>加载历史</button></div></div><p className="form-message">{message}</p>{reports.length ? reports.map((result, index) => <div className="quality-result" key={`${result.acos_percent}-${index}`}><strong>ACOS {result.acos_percent?.toFixed(2) ?? "无"}% · TACOS {result.tacos_percent?.toFixed(2) ?? "无"}% · ROI {result.roi_percent?.toFixed(2) ?? "无"}%</strong><span>异常 {result.anomalies.length} 项 · {result.incomplete ? "数据不完整" : "数据完整"}</span>{[...result.anomalies, ...result.recommendations].map((item) => <small key={item}>{item}</small>)}<em>{result.read_only ? "只读建议" : "需复核"}</em></div>) : <div className="empty-search"><strong>尚未运行广告分析</strong><span>分析不会修改预算、出价或否定词。</span></div>}</section></div>;
}
