import { BookOpen, CheckCircle, Eye, FloppyDisk, Pause, Play, Plus, Trash, UploadSimple, XCircle } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { cancelKnowledgeTask, createKnowledgeSource, createKnowledgeVersion, deleteKnowledgeSource, extractKnowledgePdfText, listKnowledgeSources, listKnowledgeTasks, listKnowledgeVersions, pauseKnowledgeSource, previewKnowledgeIngestion, publishKnowledgeVersion, rebuildKnowledgeVersion, retryKnowledgeTask, resumeKnowledgeSource, type KnowledgeIngestionResult, type KnowledgeSource, type KnowledgeTask, type KnowledgeVersion, uploadKnowledgePdf, withdrawKnowledgeSource, withdrawKnowledgeVersion } from "./api";

const STATUS_LABELS: Record<string, string> = { active: "启用", paused: "已暂停", withdrawn: "已撤回", deleted: "已删除" };
const VERSION_LABELS: Record<string, string> = { draft: "草稿", published: "已发布", withdrawn: "已撤回" };

export function KnowledgeSourcesView() {
  const [sources, setSources] = useState<KnowledgeSource[]>([]); const [selectedId, setSelectedId] = useState(""); const [versions, setVersions] = useState<KnowledgeVersion[]>([]); const [filter, setFilter] = useState("");
  const [sourceType, setSourceType] = useState("markdown"); const [title, setTitle] = useState(""); const [locator, setLocator] = useState(""); const [content, setContent] = useState("# 新知识\n\n在这里粘贴 Markdown、SQL 或文本层 PDF 内容。\n"); const [preview, setPreview] = useState<KnowledgeIngestionResult | null>(null); const [tasks, setTasks] = useState<KnowledgeTask[]>([]); const [message, setMessage] = useState(""); const [pdfStatus, setPdfStatus] = useState(""); const [busy, setBusy] = useState(false);
  const loadTextFile = async (file: File | undefined) => { if (!file) return; const lower = file.name.toLowerCase(); if (lower.endsWith(".pdf")) { setBusy(true); setSourceType("pdf"); setLocator(file.name); setTitle(file.name.replace(/\.[^.]+$/, "")); setPdfStatus("正在上传 PDF 并提取文本层…"); try { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); const uploaded = await uploadKnowledgePdf({ filename: file.name, mime_type: file.type || "application/pdf", content_base64: btoa(binary) }); if (uploaded.status !== "quarantined") throw new Error(uploaded.blocked_reason || "PDF 安全检查未通过"); const extracted = await extractKnowledgePdfText(uploaded.upload_id); setPdfStatus(`${extracted.status} · ${extracted.page_count} 页 · ${extracted.extracted_characters} 字`); if (extracted.status === "extracted") { setContent(extracted.text); setMessage("PDF 文本层已提取，可执行解析与切片预览"); } else setMessage(extracted.blocked_reason || "PDF 没有可用文本层"); } catch (error) { setPdfStatus(""); setMessage(error instanceof Error ? error.message : "PDF 提取失败"); } finally { setBusy(false); } return; } const nextType = lower.endsWith(".sql") ? "postgres_schema" : "markdown"; const reader = new FileReader(); reader.onload = () => { setSourceType(nextType); setLocator(file.name); setTitle(file.name.replace(/\.[^.]+$/, "")); setContent(String(reader.result ?? "")); setMessage(`${file.name} 已加载，可继续执行解析预览`); }; reader.onerror = () => setMessage("文件读取失败"); reader.readAsText(file);
  };
  const refresh = async () => { try { const next = await listKnowledgeSources(); setSources(next); if (!selectedId && next[0]) setSelectedId(next[0].id); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "知识源加载失败"); } };
  const refreshTasks = async () => { try { setTasks(await listKnowledgeTasks()); } catch (error) { setMessage(error instanceof Error ? error.message : "任务状态加载失败"); } };
  useEffect(() => { void refresh(); void refreshTasks(); const timer = window.setInterval(() => { void refreshTasks(); }, 5000); return () => window.clearInterval(timer); }, []); useEffect(() => { if (!selectedId) { setVersions([]); return; } void listKnowledgeVersions(selectedId).then(setVersions).catch(() => setMessage("版本列表加载失败")); }, [selectedId]);
  const visibleSources = useMemo(() => sources.filter((source) => `${source.title} ${source.source_locator} ${source.source_type}`.toLowerCase().includes(filter.toLowerCase())), [filter, sources]); const selected = sources.find((source) => source.id === selectedId);
  const ingestionPayload = (documentVersionId: string) => { const strategy = sourceType === "markdown" ? "markdown_sections" : sourceType === "postgres_schema" ? "postgres_table_fields" : "pdf_paragraphs"; return { document_id: selected?.id || `preview-${Date.now()}`, document_version_id: documentVersionId, source_type: sourceType, business_domain: sourceType === "postgres_schema" ? "database" : "general", filename: locator || `knowledge.${sourceType === "pdf" ? "pdf" : "md"}`, content, strategy, source_locator: locator || "inline" }; };
  const runPreview = async () => { setBusy(true); setMessage(""); try { setPreview(await previewKnowledgeIngestion(ingestionPayload(`preview-version-${Date.now()}`))); setMessage("解析、清洗、切片和质量门禁已完成"); } catch (error) { setMessage(error instanceof Error ? error.message : "解析预览失败"); } finally { setBusy(false); } };
  const create = async () => { if (!title.trim() || !locator.trim()) return; setBusy(true); try { const source = await createKnowledgeSource({ title: title.trim(), source_type: sourceType, business_domain: sourceType === "postgres_schema" ? "database" : "general", source_locator: locator.trim() }); setTitle(""); setSelectedId(source.id); setMessage("知识源已创建，请执行解析预览并保存版本"); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "知识源创建失败"); } finally { setBusy(false); } };
  const saveVersion = async () => { if (!selected || !preview || !preview.quality_passed) return; setBusy(true); try { const version = await createKnowledgeVersion(selected.id, { content_hash: preview.content_hash, parser_name: preview.parser_name, parser_version: "1", cleaner_version: preview.cleaner_version }); const staged = await previewKnowledgeIngestion(ingestionPayload(version.id)); if (!staged.quality_passed) throw new Error(staged.blocked_reason || "正式版本质量门禁未通过"); if (staged.content_hash !== preview.content_hash) throw new Error("内容在保存前发生变化，请重新执行预览后再保存"); setPreview(staged); setMessage("版本已保存为草稿，切片已绑定正式版本"); setVersions(await listKnowledgeVersions(selected.id)); } catch (error) { setMessage(error instanceof Error ? error.message : "版本保存失败"); } finally { setBusy(false); } };
  const changeSource = async (action: "pause" | "resume" | "withdraw" | "delete") => { if (!selected) return; setBusy(true); try { const next = action === "pause" ? await pauseKnowledgeSource(selected.id) : action === "resume" ? await resumeKnowledgeSource(selected.id) : action === "withdraw" ? await withdrawKnowledgeSource(selected.id) : await deleteKnowledgeSource(selected.id); setSources((current) => current.map((item) => item.id === next.id ? next : item)); setMessage(`知识源已${action === "delete" ? "删除" : action === "withdraw" ? "撤回" : action === "pause" ? "暂停" : "恢复"}`); } catch (error) { setMessage(error instanceof Error ? error.message : "知识源操作失败"); } finally { setBusy(false); } };
  const changeVersion = async (version: KnowledgeVersion, action: "publish" | "withdraw") => { setBusy(true); try { const next = action === "publish" ? await publishKnowledgeVersion(version.id) : await withdrawKnowledgeVersion(version.id); setVersions((current) => current.map((item) => item.id === next.id ? next : item)); setMessage(action === "publish" ? "版本已通过发布门禁" : "版本已撤回"); } catch (error) { setMessage(error instanceof Error ? error.message : "版本操作失败"); } finally { setBusy(false); } };
  const rebuild = async (version: KnowledgeVersion) => { setBusy(true); try { const task = await rebuildKnowledgeVersion(version.id); setTasks((current) => [{ task_id: task.task_id, task_type: "rebuild", organization_id: "current", source_id: selected?.id || null, document_version_id: version.id, status: task.status as KnowledgeTask["status"], attempt: 0, error_code: null }, ...current]); setMessage("索引重建任务已排队"); } catch (error) { setMessage(error instanceof Error ? error.message : "索引重建任务创建失败"); } finally { setBusy(false); } };
  return <div className="view-content">
    <div className="page-heading"><div><span className="eyebrow">知识中心 / 治理</span><h1>知识源管理</h1><p>来源、版本、解析预览、质量门禁和发布生命周期统一管理。</p></div><BookOpen size={28} /></div>
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">接入向导</span><h2>新增来源与解析预览</h2></div><UploadSimple size={24} /></div><div className="form-grid"><label>来源名称<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例如：库存同步 SOP" /></label><label>来源定位<input value={locator} onChange={(event) => setLocator(event.target.value)} placeholder="文件名、URL 或 schema 定位" /></label><label>来源类型<select value={sourceType} onChange={(event) => setSourceType(event.target.value)}><option value="markdown">Markdown</option><option value="postgres_schema">SQL / PostgreSQL Schema</option><option value="pdf">文本层 PDF</option></select></label><label>导入文本文件<input type="file" accept=".md,.markdown,.sql,.txt,.pdf" onChange={(event) => void loadTextFile(event.target.files?.[0])} /><small>Markdown/SQL/TXT 可直接读取；PDF 自动提取文本层。</small></label></div>{pdfStatus ? <p className="form-message" role="status">PDF 状态：{pdfStatus}</p> : null}<textarea aria-label="知识内容" rows={7} value={content} onChange={(event) => setContent(event.target.value)} /><div className="sync-actions"><button type="button" className="secondary-button" disabled={busy || !content.trim()} onClick={() => void runPreview()}><Eye size={16} />{busy ? "处理中…" : "解析与切片预览"}</button><button type="button" className="primary-button" disabled={busy || !title.trim() || !locator.trim()} onClick={() => void create()}><Plus size={16} />创建来源</button>{selected && preview ? <button type="button" className="secondary-button" disabled={busy || !preview.quality_passed} onClick={() => void saveVersion()}><FloppyDisk size={16} />保存草稿版本</button> : null}</div>{message ? <p className="form-message" role="status">{message}</p> : null}{preview ? <div className="quality-result"><strong>{preview.quality_passed ? "质量门禁通过" : "质量门禁阻断"} · {preview.chunks.length} 个切片</strong><span>{preview.parser_name} · {preview.content_hash.slice(0, 16)}…</span>{preview.blocked_reason ? <em>{preview.blocked_reason}</em> : null}{preview.chunks.slice(0, 3).map((chunk) => <article className="operation-row" key={chunk.chunk_id}><span><strong>#{chunk.ordinal + 1} {chunk.title_path.join(" / ")}</strong><small>{chunk.content.slice(0, 160)}</small></span><em>可检索预览</em></article>)}</div> : null}</section>
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">目录与筛选</span><h2>已接入来源</h2></div><input aria-label="筛选知识源" placeholder="筛选来源名称、类型或定位" value={filter} onChange={(event) => setFilter(event.target.value)} /></div>{visibleSources.length ? visibleSources.map((source) => <article className={`operation-row ${selectedId === source.id ? "selected-row" : ""}`} key={source.id} onClick={() => setSelectedId(source.id)}><span><strong>{source.title}</strong><small>{source.source_locator} · {source.source_type} · 权威级别 {source.authority_level}</small></span><em>{STATUS_LABELS[source.status] ?? source.status}</em></article>) : <div className="empty-search"><BookOpen size={24} /><strong>暂无匹配知识源</strong><span>支持空数据、筛选无结果和权限错误提示。</span></div>}</section>
    {selected ? <section className="panel"><div className="section-heading"><div><span className="eyebrow">版本详情</span><h2>{selected.title}</h2></div><div className="sync-actions"><button className="text-button" disabled={busy || selected.status !== "active"} onClick={() => void changeSource(selected.status === "paused" ? "resume" : "pause")}>{selected.status === "paused" ? <Play size={15} /> : <Pause size={15} />}{selected.status === "paused" ? "恢复" : "暂停"}</button><button className="text-button" disabled={busy} onClick={() => void changeSource("withdraw")}><XCircle size={15} />撤回</button><button className="text-button danger-button" disabled={busy} onClick={() => void changeSource("delete")}><Trash size={15} />删除</button></div></div>{versions.length ? versions.map((version) => <article className="operation-row" key={version.id}><span><strong>v{version.version_number} · {VERSION_LABELS[version.status] ?? version.status}</strong><small>{version.parser_name} · 清洗器 {version.cleaner_version} · {version.content_hash.slice(0, 24)}…</small></span>{version.status === "draft" ? <button className="text-button" disabled={busy} onClick={() => void changeVersion(version, "publish")}><CheckCircle size={15} />发布</button> : version.status === "published" ? <button className="text-button" disabled={busy} onClick={() => void changeVersion(version, "withdraw")}><XCircle size={15} />撤回</button> : null}<button className="text-button" disabled={busy || version.status === "withdrawn"} onClick={() => void rebuild(version)}><BookOpen size={15} />重建索引</button></article>) : <div className="empty-search"><strong>暂无版本</strong><span>解析通过后保存草稿版本，发布前必须通过质量门禁。</span></div>}</section> : null}
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">异步任务</span><h2>解析、切片与索引状态</h2></div></div>{tasks.length ? tasks.slice(0, 8).map((task) => <article className="operation-row" key={task.task_id}><span><strong>{task.task_type} · {task.status}</strong><small>{task.document_version_id ? `版本 ${task.document_version_id.slice(0, 12)}… · ` : ""}{task.task_id} · 尝试 {task.attempt}{task.error_code ? ` · ${task.error_code}` : ""}</small></span>{task.status === "queued" || task.status === "running" ? <button className="text-button" disabled={busy} onClick={() => void cancelKnowledgeTask(task.task_id).then((next) => setTasks((current) => current.map((item) => item.task_id === next.task_id ? next : item))).catch(() => setMessage("任务取消失败"))}>取消</button> : task.status === "failed" || task.status === "cancelled" ? <button className="text-button" disabled={busy} onClick={() => void retryKnowledgeTask(task.task_id).then((next) => setTasks((current) => current.map((item) => item.task_id === next.task_id ? next : item))).catch(() => setMessage("任务重试失败"))}>重试</button> : null}</article>) : <div className="empty-search"><strong>暂无异步任务</strong><span>发布、撤回和重建任务状态会持久化在 PostgreSQL。</span></div>}</section>
  </div>;
}
