import { useState } from "react";
import { confirmDecisionBook, generateAndSaveDecisionBook, listDecisionBooks, type SelectionDecisionBook } from "./api";

const draft: SelectionDecisionBook = { opportunity_summary: "搜索热度与覆盖缺口形成机会", customer_scene: "通勤与户外使用", market_sample: "公开样本 5 个，采样估算", competitor_snapshots: ["竞品 A：1999 RUB，评分 4.8"], profit_calculation: "FBO/FBS 利润模型已完成", risks: ["认证要求需人工确认", "样本不代表全市场"], price_range: "1999-2499 RUB", stock_recommendation: "首批小批量测试", seed_keywords: ["термос", "термос стальной"], data_sources: ["operator_imported", "public_sample", "derived_estimate"], uncertainty: "公开市场指标为受控样本估算", confirmation_status: "pending" };

export function SelectionDecisionBookView({ workspaceId }: { workspaceId: string }) {
  const [book, setBook] = useState<SelectionDecisionBook | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("人工确认前不执行任何外部写入");
  const run = async () => { setBusy(true); try { setBook(await generateAndSaveDecisionBook(workspaceId, draft)); setMessage("决策书已生成并保存"); } catch (error) { setMessage(error instanceof Error ? error.message : "生成失败"); } finally { setBusy(false); } };
  const load = async () => { setBusy(true); try { const books = await listDecisionBooks(workspaceId); setBook(books[0] ?? null); setMessage(books.length ? "已加载最近决策书" : "暂无历史决策书"); } catch (error) { setMessage(error instanceof Error ? error.message : "加载失败"); } finally { setBusy(false); } };
  const confirm = async (status: "confirmed" | "rejected") => { if (!book) return; setBusy(true); try { setBook(await confirmDecisionBook(workspaceId, { ...book, confirmation_status: status })); setMessage(status === "confirmed" ? "已人工确认" : "已驳回"); } catch (error) { setMessage(error instanceof Error ? error.message : "确认失败"); } finally { setBusy(false); } };
  return <div className="view-content"><section className="page-heading compact"><div><p className="eyebrow">选品 Skill / SEL-008 / SEL-009</p><h1>商品立项决策书</h1><p>汇总机会、竞品、FBO/FBS 利润、风险、来源和不确定性；人工确认前不触发采购、上架或广告写入。</p></div></section><section className="panel import-panel"><div className="button-row"><button className="secondary-button" disabled={busy} onClick={() => void run()}>生成并保存决策书</button><button className="secondary-button" disabled={busy} onClick={() => void load()}>加载历史决策书</button></div><p className="form-message">{message}</p>{book ? <div className="quality-result"><strong>状态：{book.confirmation_status} · {book.opportunity_summary}</strong><span>客户场景：{book.customer_scene} · 价格区间：{book.price_range}</span><span>市场样本：{book.market_sample} · 利润测算：{book.profit_calculation}</span><small>竞品：{book.competitor_snapshots.join("；")}</small><small>风险：{book.risks.join("；")}</small><small>首批备货：{book.stock_recommendation} · 种子词：{book.seed_keywords.join("、")}</small><small>来源：{book.data_sources.join("、")} · {book.uncertainty}</small><div className="sync-actions"><button className="secondary-button" disabled={busy || book.confirmation_status !== "pending"} onClick={() => void confirm("confirmed")}>人工确认</button><button className="text-button" disabled={busy || book.confirmation_status !== "pending"} onClick={() => void confirm("rejected")}>驳回</button></div></div> : <div className="empty-search"><strong>尚未生成决策书</strong><span>决策书只生成建议，不自动触发外部动作。</span></div>}</section></div>;
}
